package com.googlecode.objectify.cmd;

import java.util.Map;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.Result;


/**
 * <p>The top element in the command chain for saving entities in the datastore.</p>
 * 
 * @author Jeff Schnitzer <jeff@infohazard.org>
 */
public interface Put
{
	/**
	 * <p>Asynchronously save a single entity in the datastore.<p>
	 * 
	 * <p>If the entity has a null Long id, the value will be autogenerated and populated on the entity object
	 * when the async operation completes.  If you require this value, call now() on the result.</p>
	 * 
	 * <p>Puts do not cascade.</p>
	 *  
	 * @param entity must be a registered entity type
	 * @return an asynchronous result.  To force a synchronous save, call Result.now().
	 */
	<K, E extends K> Result<Key<K>> entity(E entity);
	
	/**
	 * <p>Asynchronously save a batch of entities in the datastore.</p>
	 * 
	 * <p>If any entities have null Long ids, the values will be autogenerated and populated on the entity objects
	 * when the async operation completes.  If you require these values, call now() on the result.</p>
	 * 
	 * <p>Puts do not cascade.</p>
	 *  
	 * @param entities must be registered entity types
	 * @return an asynchronous result.  To force a synchronous save, call Result.now().
	 */
	<K, E extends K> Result<Map<Key<K>, E>> entities(Iterable<? extends E> entities);
	
	/**
	 * A convenience method for entities(Iterable)
	 */
	<K, E extends K> Result<Map<Key<K>, E>> entities(E... entities);
}
